
-- Insert sample jobs
INSERT INTO jobs (title, company, location, salary, job_type, description, requirements, status) VALUES
('Senior Software Engineer', 'Ethio Telecom', 'Addis Ababa', '45,000 - 65,000 ETB/month', 'full-time', 'We are looking for an experienced Software Engineer to join our technology team. You will be responsible for developing and maintaining enterprise-level applications.', 'Bachelor''s degree in Computer Science or related field. 5+ years of experience in software development. Proficiency in Java, Python, or similar languages.', 'approved'),
('Marketing Manager', 'Ethiopian Airlines', 'Addis Ababa', '35,000 - 50,000 ETB/month', 'full-time', 'Lead our marketing initiatives and develop strategies to increase brand awareness and customer engagement across Africa and beyond.', 'MBA in Marketing or related field. 4+ years of marketing experience. Strong communication and leadership skills.', 'approved'),
('Financial Analyst', 'Commercial Bank of Ethiopia', 'Addis Ababa', '30,000 - 45,000 ETB/month', 'full-time', 'Analyze financial data and provide insights to support business decisions. Prepare reports and forecasts for senior management.', 'Bachelor''s degree in Finance, Accounting, or Economics. 3+ years of experience in financial analysis. Excel and data analysis skills.', 'approved'),
('Civil Engineer', 'China Road and Bridge Corporation', 'Dire Dawa', '40,000 - 55,000 ETB/month', 'contract', 'Oversee road construction projects, ensure quality standards, and manage project timelines and resources.', 'Bachelor''s degree in Civil Engineering. 5+ years of experience in road construction. Valid engineering license.', 'approved'),
('HR Coordinator', 'Dashen Bank', 'Hawassa', '25,000 - 35,000 ETB/month', 'full-time', 'Support HR operations including recruitment, onboarding, employee relations, and performance management.', 'Bachelor''s degree in HR Management or Business Administration. 2+ years of HR experience. Knowledge of labor laws.', 'approved'),
('Data Scientist', 'Safaricom Ethiopia', 'Addis Ababa', '50,000 - 70,000 ETB/month', 'full-time', 'Apply machine learning and statistical techniques to analyze large datasets and drive business insights.', 'Master''s degree in Data Science, Statistics, or related field. Experience with Python, R, and ML frameworks. Strong analytical skills.', 'approved');

-- Insert sample tenders
INSERT INTO tenders (title, organization, bid_guarantee, deadline, sector, region, description, requirements, status) VALUES
('Road Construction Project - Addis-Adama Expressway Extension', 'Ethiopian Roads Authority', '5,000,000 ETB', '2025-02-15', 'Construction', 'Addis Ababa', 'Construction of 50km expressway extension connecting Addis Ababa to Adama with modern road infrastructure including bridges and drainage systems.', 'Valid Grade 1 Road Contractor license. Minimum 10 years experience in highway construction. Equipment ownership verification required.', 'approved'),
('Hospital Equipment Supply and Installation', 'Ministry of Health', '2,500,000 ETB', '2025-01-30', 'Healthcare', 'Nationwide', 'Supply and installation of medical equipment for 5 regional hospitals including MRI machines, X-ray systems, and laboratory equipment.', 'Valid medical equipment import license. ISO certification for medical devices. After-sales service capability.', 'approved'),
('IT Infrastructure Modernization', 'National Bank of Ethiopia', '3,000,000 ETB', '2025-02-28', 'IT', 'Addis Ababa', 'Complete overhaul of IT infrastructure including server upgrades, network security implementation, and cloud migration services.', 'Certified IT service provider. Experience with banking systems. ISO 27001 certification required.', 'approved'),
('Agricultural Equipment Procurement', 'Ministry of Agriculture', '1,500,000 ETB', '2025-01-25', 'Agriculture', 'Oromia Region', 'Procurement of tractors, harvesters, and irrigation equipment for agricultural development programs in Oromia region.', 'Authorized dealer for agricultural machinery. Spare parts availability guarantee. Training service capability.', 'approved'),
('School Building Construction', 'Ministry of Education', '4,000,000 ETB', '2025-03-15', 'Construction', 'Amhara Region', 'Construction of 10 primary school buildings with modern facilities including classrooms, libraries, and sanitation facilities.', 'Grade 3 or above building contractor license. Experience in educational facility construction. Local workforce utilization plan.', 'approved'),
('Water Treatment Plant Upgrade', 'Addis Ababa Water and Sewerage Authority', '6,000,000 ETB', '2025-02-20', 'Infrastructure', 'Addis Ababa', 'Upgrade of Legedadi water treatment plant to increase capacity and improve water quality for the growing population.', 'Experience in water treatment projects. Environmental impact assessment capability. International quality standards compliance.', 'approved');

-- Insert sample scholarships
INSERT INTO scholarships (title, organization, level, field, amount, location, deadline, application_url, description, requirements, benefits, status) VALUES
('Mastercard Foundation Scholars Program', 'University of Gondar', 'undergraduate', 'All Fields', 'Full Tuition + Living Expenses', 'Ethiopia', '2025-03-31', 'https://mcfsp.ug.edu.et', 'Comprehensive scholarship for academically talented but economically disadvantaged students to pursue undergraduate studies at University of Gondar.', ARRAY['Ethiopian nationality', 'Secondary school completion with high grades', 'Demonstrated financial need', 'Strong leadership potential'], ARRAY['Full tuition coverage', 'Monthly stipend', 'Accommodation', 'Book allowance', 'Mentorship program'], 'approved'),
('DAAD Ethiopian Graduate Scholarship', 'German Academic Exchange Service (DAAD)', 'masters', 'Engineering & Technology', '€1,200/month + Tuition', 'Germany', '2025-02-15', 'https://www.daad.de/en/', 'Scholarship for Ethiopian graduates to pursue Master''s degrees in Engineering and Technology fields at German universities.', ARRAY['Bachelor''s degree with distinction', 'Minimum 2 years work experience', 'English/German proficiency', 'Letter of admission from German university'], ARRAY['Monthly stipend', 'Tuition fee waiver', 'Travel allowance', 'Health insurance', 'German language course'], 'approved'),
('African Union Commission Scholarship', 'African Union', 'phd', 'Science & Research', 'Full Funding', 'Pan-African', '2025-04-30', 'https://au.int/scholarships', 'PhD scholarship for African researchers to conduct research in priority areas aligned with Agenda 2063 goals.', ARRAY['Master''s degree in relevant field', 'Research proposal approval', 'Publication track record', 'African citizenship'], ARRAY['Full tuition', 'Research grant', 'Conference participation', 'Publication support', 'International exposure'], 'approved'),
('Chevening Scholarship Ethiopia', 'UK Government', 'masters', 'Public Policy & Governance', 'Full Funding', 'United Kingdom', '2025-01-31', 'https://www.chevening.org', 'Prestigious UK government scholarship for future leaders to study one-year Master''s programs at UK universities.', ARRAY['Bachelor''s degree', 'Minimum 2 years work experience', 'Leadership qualities', 'Return to Ethiopia commitment'], ARRAY['Full university fees', 'Monthly stipend', 'Travel costs', 'Thesis grant', 'Networking events'], 'approved'),
('AAU Merit Scholarship', 'Addis Ababa University', 'undergraduate', 'Medicine & Health Sciences', '100% Tuition Waiver', 'Addis Ababa, Ethiopia', '2025-09-01', 'https://www.aau.edu.et/scholarships', 'Merit-based scholarship for top-performing students enrolling in medical and health science programs at AAU.', ARRAY['Ethiopian national entrance exam top 1%', 'Science stream background', 'Interview selection', 'Health fitness certificate'], ARRAY['Full tuition waiver', 'Priority registration', 'Library access', 'Research opportunities'], 'approved'),
('Fulbright Foreign Student Program', 'U.S. Department of State', 'masters', 'All Fields', 'Full Funding', 'United States', '2025-02-28', 'https://et.usembassy.gov/fulbright', 'Premier educational exchange program providing Ethiopian students opportunities to study in the United States.', ARRAY['Bachelor''s degree', 'TOEFL score 80+', 'Strong academic record', 'Community involvement'], ARRAY['Full tuition', 'Living stipend', 'Health insurance', 'Round-trip airfare', 'Cultural programs'], 'approved');
