// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzjfbqirbxsqdwcbpsst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6amZicWlyYnhzcWR3Y2Jwc3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjU5MjAsImV4cCI6MjA2NjAwMTkyMH0.JAHqjJEWxTApCs2AHAAOpH7_-HUPWU0GmLt2UgXht9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);