name: Create Release

on:
  # Trigger on version tags
  push:
    tags:
      - 'v*.*.*'
  
  # Allow manual release creation
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for GitHub Pages
        run: npm run build
        env:
          NODE_ENV: production
          VITE_SUPABASE_URL: https://qzjfbqirbxsqdwcbpsst.supabase.co
          VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6amZicWlyYnhzcWR3Y2Jwc3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjU5MjAsImV4cCI6MjA2NjAwMTkyMH0.JAHqjJEWxTApCs2AHAAOpH7_-HUPWU0GmLt2UgXht9w

      - name: Create GitHub Pages package
        run: |
          cd dist
          zip -r ../github-pages-${{ github.ref_name }}.zip .
          cd ..

      - name: Build for cPanel
        run: |
          export DEPLOY_TARGET=cpanel
          npm run build
          cd dist
          zip -r ../cpanel-hosting-${{ github.ref_name }}.zip .
          cd ..

      - name: Generate changelog
        run: |
          echo "# Release Notes for ${{ github.ref_name }}" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## 🚀 Deployment Packages" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "### GitHub Pages Deployment" >> RELEASE_NOTES.md
          echo "- Download: \`github-pages-${{ github.ref_name }}.zip\`" >> RELEASE_NOTES.md
          echo "- Auto-deploys to: ${{ github.server_url }}/${{ github.repository }}/deployments" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "### cPanel Hosting" >> RELEASE_NOTES.md
          echo "- Download: \`cpanel-hosting-${{ github.ref_name }}.zip\`" >> RELEASE_NOTES.md
          echo "- Extract to your public_html folder" >> RELEASE_NOTES.md
          echo "- Includes .htaccess for SPA routing" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## 📋 Installation Instructions" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "### For cPanel:" >> RELEASE_NOTES.md
          echo "1. Download \`cpanel-hosting-${{ github.ref_name }}.zip\`" >> RELEASE_NOTES.md
          echo "2. Login to cPanel File Manager" >> RELEASE_NOTES.md
          echo "3. Navigate to public_html" >> RELEASE_NOTES.md
          echo "4. Upload and extract the zip file" >> RELEASE_NOTES.md
          echo "5. Ensure .htaccess file is present" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "### Features in this release:" >> RELEASE_NOTES.md
          echo "- ✅ Optimized build with ES2020 support" >> RELEASE_NOTES.md
          echo "- ✅ Supabase backend integration" >> RELEASE_NOTES.md
          echo "- ✅ Responsive design with Tailwind CSS" >> RELEASE_NOTES.md
          echo "- ✅ React Router for navigation" >> RELEASE_NOTES.md
          echo "- ✅ SEO optimized" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "Generated on: $(date)" >> RELEASE_NOTES.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            github-pages-${{ github.ref_name }}.zip
            cpanel-hosting-${{ github.ref_name }}.zip
          body_path: RELEASE_NOTES.md
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist